services:
  psql:
    image: pgvector/pgvector:pg16
    container_name: psql-ym
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ym
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mysql:
    image: mysql:8.0.44
    container_name: mysql-ym
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ym
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql
    labels:
      createdBy: "Apps"
    command:
      - --default-authentication-plugin=mysql_native_password
networks:
  default:
    name: ym
    external: true